FROM golang:1.11
ADD . /go/src/github.com/insolar/insolar
WORKDIR /go/src/github.com/insolar/insolar
RUN apt-get update && apt-get -y install jq && apt-get clean && rm -Rf /go/src/github.com/insolar/insolar/vendor/* && make install-deps && make pre-build && mv /go/src/github.com/insolar/insolar/vendor /go/
