package executor

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/insolar/insolar/insolar"
)

// JetWaiterMock implements JetWaiter
type JetWaiterMock struct {
	t minimock.Tester

	funcWait          func(ctx context.Context, jetID insolar.JetID, pulse insolar.PulseNumber) (err error)
	inspectFuncWait   func(ctx context.Context, jetID insolar.JetID, pulse insolar.PulseNumber)
	afterWaitCounter  uint64
	beforeWaitCounter uint64
	WaitMock          mJetWaiterMockWait
}

// NewJetWaiterMock returns a mock for JetWaiter
func NewJetWaiterMock(t minimock.Tester) *JetWaiterMock {
	m := &JetWaiterMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.WaitMock = mJetWaiterMockWait{mock: m}
	m.WaitMock.callArgs = []*JetWaiterMockWaitParams{}

	return m
}

type mJetWaiterMockWait struct {
	mock               *JetWaiterMock
	defaultExpectation *JetWaiterMockWaitExpectation
	expectations       []*JetWaiterMockWaitExpectation

	callArgs []*JetWaiterMockWaitParams
	mutex    sync.RWMutex
}

// JetWaiterMockWaitExpectation specifies expectation struct of the JetWaiter.Wait
type JetWaiterMockWaitExpectation struct {
	mock    *JetWaiterMock
	params  *JetWaiterMockWaitParams
	results *JetWaiterMockWaitResults
	Counter uint64
}

// JetWaiterMockWaitParams contains parameters of the JetWaiter.Wait
type JetWaiterMockWaitParams struct {
	ctx   context.Context
	jetID insolar.JetID
	pulse insolar.PulseNumber
}

// JetWaiterMockWaitResults contains results of the JetWaiter.Wait
type JetWaiterMockWaitResults struct {
	err error
}

// Expect sets up expected params for JetWaiter.Wait
func (mmWait *mJetWaiterMockWait) Expect(ctx context.Context, jetID insolar.JetID, pulse insolar.PulseNumber) *mJetWaiterMockWait {
	if mmWait.mock.funcWait != nil {
		mmWait.mock.t.Fatalf("JetWaiterMock.Wait mock is already set by Set")
	}

	if mmWait.defaultExpectation == nil {
		mmWait.defaultExpectation = &JetWaiterMockWaitExpectation{}
	}

	mmWait.defaultExpectation.params = &JetWaiterMockWaitParams{ctx, jetID, pulse}
	for _, e := range mmWait.expectations {
		if minimock.Equal(e.params, mmWait.defaultExpectation.params) {
			mmWait.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmWait.defaultExpectation.params)
		}
	}

	return mmWait
}

// Inspect accepts an inspector function that has same arguments as the JetWaiter.Wait
func (mmWait *mJetWaiterMockWait) Inspect(f func(ctx context.Context, jetID insolar.JetID, pulse insolar.PulseNumber)) *mJetWaiterMockWait {
	if mmWait.mock.inspectFuncWait != nil {
		mmWait.mock.t.Fatalf("Inspect function is already set for JetWaiterMock.Wait")
	}

	mmWait.mock.inspectFuncWait = f

	return mmWait
}

// Return sets up results that will be returned by JetWaiter.Wait
func (mmWait *mJetWaiterMockWait) Return(err error) *JetWaiterMock {
	if mmWait.mock.funcWait != nil {
		mmWait.mock.t.Fatalf("JetWaiterMock.Wait mock is already set by Set")
	}

	if mmWait.defaultExpectation == nil {
		mmWait.defaultExpectation = &JetWaiterMockWaitExpectation{mock: mmWait.mock}
	}
	mmWait.defaultExpectation.results = &JetWaiterMockWaitResults{err}
	return mmWait.mock
}

//Set uses given function f to mock the JetWaiter.Wait method
func (mmWait *mJetWaiterMockWait) Set(f func(ctx context.Context, jetID insolar.JetID, pulse insolar.PulseNumber) (err error)) *JetWaiterMock {
	if mmWait.defaultExpectation != nil {
		mmWait.mock.t.Fatalf("Default expectation is already set for the JetWaiter.Wait method")
	}

	if len(mmWait.expectations) > 0 {
		mmWait.mock.t.Fatalf("Some expectations are already set for the JetWaiter.Wait method")
	}

	mmWait.mock.funcWait = f
	return mmWait.mock
}

// When sets expectation for the JetWaiter.Wait which will trigger the result defined by the following
// Then helper
func (mmWait *mJetWaiterMockWait) When(ctx context.Context, jetID insolar.JetID, pulse insolar.PulseNumber) *JetWaiterMockWaitExpectation {
	if mmWait.mock.funcWait != nil {
		mmWait.mock.t.Fatalf("JetWaiterMock.Wait mock is already set by Set")
	}

	expectation := &JetWaiterMockWaitExpectation{
		mock:   mmWait.mock,
		params: &JetWaiterMockWaitParams{ctx, jetID, pulse},
	}
	mmWait.expectations = append(mmWait.expectations, expectation)
	return expectation
}

// Then sets up JetWaiter.Wait return parameters for the expectation previously defined by the When method
func (e *JetWaiterMockWaitExpectation) Then(err error) *JetWaiterMock {
	e.results = &JetWaiterMockWaitResults{err}
	return e.mock
}

// Wait implements JetWaiter
func (mmWait *JetWaiterMock) Wait(ctx context.Context, jetID insolar.JetID, pulse insolar.PulseNumber) (err error) {
	mm_atomic.AddUint64(&mmWait.beforeWaitCounter, 1)
	defer mm_atomic.AddUint64(&mmWait.afterWaitCounter, 1)

	if mmWait.inspectFuncWait != nil {
		mmWait.inspectFuncWait(ctx, jetID, pulse)
	}

	mm_params := &JetWaiterMockWaitParams{ctx, jetID, pulse}

	// Record call args
	mmWait.WaitMock.mutex.Lock()
	mmWait.WaitMock.callArgs = append(mmWait.WaitMock.callArgs, mm_params)
	mmWait.WaitMock.mutex.Unlock()

	for _, e := range mmWait.WaitMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmWait.WaitMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmWait.WaitMock.defaultExpectation.Counter, 1)
		mm_want := mmWait.WaitMock.defaultExpectation.params
		mm_got := JetWaiterMockWaitParams{ctx, jetID, pulse}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmWait.t.Errorf("JetWaiterMock.Wait got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmWait.WaitMock.defaultExpectation.results
		if mm_results == nil {
			mmWait.t.Fatal("No results are set for the JetWaiterMock.Wait")
		}
		return (*mm_results).err
	}
	if mmWait.funcWait != nil {
		return mmWait.funcWait(ctx, jetID, pulse)
	}
	mmWait.t.Fatalf("Unexpected call to JetWaiterMock.Wait. %v %v %v", ctx, jetID, pulse)
	return
}

// WaitAfterCounter returns a count of finished JetWaiterMock.Wait invocations
func (mmWait *JetWaiterMock) WaitAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmWait.afterWaitCounter)
}

// WaitBeforeCounter returns a count of JetWaiterMock.Wait invocations
func (mmWait *JetWaiterMock) WaitBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmWait.beforeWaitCounter)
}

// Calls returns a list of arguments used in each call to JetWaiterMock.Wait.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmWait *mJetWaiterMockWait) Calls() []*JetWaiterMockWaitParams {
	mmWait.mutex.RLock()

	argCopy := make([]*JetWaiterMockWaitParams, len(mmWait.callArgs))
	copy(argCopy, mmWait.callArgs)

	mmWait.mutex.RUnlock()

	return argCopy
}

// MinimockWaitDone returns true if the count of the Wait invocations corresponds
// the number of defined expectations
func (m *JetWaiterMock) MinimockWaitDone() bool {
	for _, e := range m.WaitMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.WaitMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterWaitCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcWait != nil && mm_atomic.LoadUint64(&m.afterWaitCounter) < 1 {
		return false
	}
	return true
}

// MinimockWaitInspect logs each unmet expectation
func (m *JetWaiterMock) MinimockWaitInspect() {
	for _, e := range m.WaitMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to JetWaiterMock.Wait with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.WaitMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterWaitCounter) < 1 {
		if m.WaitMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to JetWaiterMock.Wait")
		} else {
			m.t.Errorf("Expected call to JetWaiterMock.Wait with params: %#v", *m.WaitMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcWait != nil && mm_atomic.LoadUint64(&m.afterWaitCounter) < 1 {
		m.t.Error("Expected call to JetWaiterMock.Wait")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *JetWaiterMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockWaitInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *JetWaiterMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *JetWaiterMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockWaitDone()
}
