{
 "title": "INS-Heavy node",
 "tags": [ "INS" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "installation",
    "query": "label_values(insolar_light_last_sent_pulse, installation)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current pulse",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "insolar_current_pulse{role=\"heavy_material\", installation=\"$installation\"}"
    }
   ]
  },
  {
   "title": "Last fully finalized pulse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "insolar_heavy_finalized_pulse{installation=\"$installation\"}"
    }
   ]
  },
  {
   "title": "Finalized pulse delta",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(insolar_current_pulse{role=\"heavy_material\", installation=\"$installation\"} - insolar_heavy_finalized_pulse{role=\"heavy_material\", installation=\"$installation\"}) / 10"
    }
   ]
  },
  {
   "title": "Badger open time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "insolar_badger_start_time{role=\"heavy_material\", installation=\"$installation\"}"
    }
   ]
  },
  {
   "title": "heavy payload messages rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(insolar_heavysyncer_heavypayload_count{installation=\"$installation\"}[1m])"
    }
   ]
  },
  {
   "title": "TypeReplication messages sent from all nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_bus_sent_total{message_type=\"TypeReplication\", installation=\"$installation\"}[1m]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Abandoned requests per pulse",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(insolar_requests_abandoned{role=\"heavy_material\", installation=\"$installation\"}[1m])*10"
    }
   ]
  },
  {
   "title": "Record export timing",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(increase(insolar_heavy_exporter_method_timing_bucket{heavy_exporter_method_name=\"record-export\", installation=\"$installation\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Pulse export timing",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "sum(increase(insolar_heavy_exporter_method_timing_bucket{heavy_exporter_method_name=\"pulse-export\", installation=\"$installation\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Top sync pulse timing",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "sum(increase(insolar_heavy_exporter_method_timing_bucket{heavy_exporter_method_name=\"pulse-top-sync-pulse\", installation=\"$installation\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Backup Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(insolar_backup_time_sum{installation=\"$installation\"}[1m])/rate(insolar_backup_time_count{installation=\"$installation\"}[1m])"
    }
   ]
  },
  {
   "title": "Badger's value GC Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(insolar_badger_value_gc_time_sum{installation=\"$installation\"}[1m])/rate(insolar_badger_value_gc_time_count{installation=\"$installation\"}[1m])"
    }
   ]
  }
 ]
}