{
 "title": "INS-Network",
 "tags": [ "INS" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "installation",
    "query": "label_values(insolar_light_last_sent_pulse, installation)"
   },
   { "name": "phase", "query": "ph1, ph2, ph3" },
   {
    "name": "packetType",
    "query": "label_values(insolar_network_futures, packetType)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pulse deviation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(insolar_current_pulse{installation=\"$installation\"}[60s])",
     "legendFormat": "P {{instance}}"
    }
   ]
  },
  {
   "title": "Active list size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "insolar_consensus_active_nodes_count{installation=\"$installation\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consensus packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(irate(insolar_consensus_packets_recv_count{phase=~\"$phase\", installation=\"$installation\"}[60s]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "-sum by(instance)(irate(insolar_consensus_packets_sent_count{phase=~\"$phase\", installation=\"$installation\"}[60s]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consensus size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(insolar_consensus_packets_recv_bytes{installation=\"$installation\"}[60s])",
     "legendFormat": "IN {{instance}} {{phase}}"
    },
    {
     "expr": "-irate(insolar_consensus_packets_sent_bytes{installation=\"$installation\"}[60s])",
     "legendFormat": "OUT {{instance}} {{phase}}"
    }
   ]
  },
  {
   "title": "Network state",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "insolar_network_state{installation=\"$installation\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "insolar_network_connections{installation=\"$installation\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Packet exchange",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(insolar_network_recv_bytes_count{installation=\"$installation\"}[60s])",
     "legendFormat": "RCV {{instance}}"
    },
    {
     "expr": "-irate(insolar_network_sent_bytes_count{installation=\"$installation\"}[60s])",
     "legendFormat": "SNT {{instance}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(insolar_network_recv_bytes_sum{installation=\"$installation\"}[60s])",
     "legendFormat": "RCV {{instance}}"
    },
    {
     "expr": "-irate(insolar_network_sent_bytes_sum{installation=\"$installation\"}[60s])",
     "legendFormat": "SNT {{instance}}"
    }
   ]
  },
  {
   "title": "Futures count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(insolar_network_futures{packetType=~\"$packetType\", installation=\"$installation\"}[60s])",
     "legendFormat": "{{instance}} {{packetType}}"
    }
   ]
  }
 ]
}