{
 "title": "INS-Flow dispatcher",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "type",
    "label": "message type",
    "query": "label_values(insolar_flow_dispatcher_handler_latency_count, message_type)"
   },
   {
    "name": "instance",
    "query": "label_values(insolar_flow_dispatcher_handler_latency_count, instance)"
   },
   {
    "name": "result",
    "query": "label_values(insolar_flow_dispatcher_handler_latency_count, result)"
   }
  ]
 },
 "panels": [
  {
   "title": "Process 1m rate of \"$type\" ($instance)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_flow_dispatcher_process_latency_bucket{message_type=~\"$type\", instance=~\"$instance\", result=~\"$result\"}[1m]))",
     "legendFormat": "{{ result }}"
    }
   ]
  },
  {
   "title": "Handlers 1m rate of \"$type\" ($instance)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_flow_dispatcher_handler_latency_count{message_type=~\"$type\", instance=~\"$instance\", result=~\"$result\"}[1m]))",
     "legendFormat": "{{ result }}"
    }
   ]
  },
  {
   "title": "Process latency \"$type\" ($instance)",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(insolar_flow_dispatcher_process_latency_bucket{message_type=~\"$type\", instance=~\"$instance\", result=~\"$result\"}) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Handler latency \"$type\" ($instance)",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(insolar_flow_dispatcher_handler_latency_bucket{message_type=~\"$type\", instance=~\"$instance\", result=~\"$result\"}) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Process cancelled 1m rate \"$type\" ($instance)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(insolar_flow_dispatcher_process_latency_count{message_type=~\"$type\", instance=~\"$instance\", result=\"cancelled\"}[1m]))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Handler cancelled 1m rate \"$type\" ($instance)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(insolar_flow_dispatcher_handler_latency_count{message_type=~\"$type\", instance=~\"$instance\", result=\"cancelled\"}[1m]))",
     "legendFormat": "{{ job }}"
    }
   ]
  }
 ]
}