{
 "title": "INS-Heavy node",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Current pulse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "insolar_current_pulse{role=\"heavy_material\"}"
    }
   ]
  },
  {
   "title": "Last fully finalized pulse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "insolar_heavy_finalized_pulse" }
   ]
  },
  {
   "title": "Finalized pulse delta",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 17, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(insolar_current_pulse{role=\"heavy_material\"} - insolar_heavy_finalized_pulse{role=\"heavy_material\"}) / 10"
    }
   ]
  },
  {
   "title": "heavy payload messages rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(insolar_heavysyncer_heavypayload_count[1m])"
    }
   ]
  },
  {
   "title": "TypeReplication messages sent from all nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_bus_sent_total{message_type=\"TypeReplication\"}[1m]))",
     "legendFormat": "rps"
    }
   ]
  }
 ]
}