{
 "title": "INS-Network",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "installation",
    "query": "\"\", \"dev-main\""
   },
   { "name": "phase", "query": "ph1, ph2, ph3" },
   {
    "name": "packetType",
    "query": "label_values(insolar_network_futures, packetType)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pulse derivation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(insolar_current_pulse{job=\"insolard\"}[60s])",
     "legendFormat": "P {{instance}}"
    }
   ]
  },
  {
   "title": "active list size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "insolar_consensus_active_nodes_count",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Consensus packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(delta(insolar_consensus_packets_recv_count{phase=~\"$phase\"}[60s]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "-sum by(instance)(delta(insolar_consensus_packets_sent_count{phase=~\"$phase\"}[60s]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consensus avg bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(insolar_consensus_packets_recv_bytes[60s])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "-deriv(insolar_consensus_packets_sent_bytes[60s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "network state",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "insolar_network_state", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "insolar_network_connections", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Packet exchange",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(insolar_network_recv_bytes_count[60s])",
     "legendFormat": "RCV {{instance}}"
    },
    {
     "expr": "-rate(insolar_network_sent_bytes_count[60s])",
     "legendFormat": "SNT {{instance}}"
    }
   ]
  },
  {
   "title": "futures count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(insolar_network_futures{packetType=~\"$packetType\"}[60s])",
     "legendFormat": "{{instance}} {{packetType}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(insolar_network_recv_bytes_sum[60s])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "-rate(insolar_network_sent_bytes_sum[60s])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}