{
 "title": "INS-Pulsar",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "installation",
    "query": "label_values(insolar_light_last_sent_pulse, installation)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current pulse",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "insolar_pulsar_current_pulse{installation=\"$installation\"}"
    }
   ]
  },
  {
   "title": "Errors while sending pulse",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "insolar_pulsar_sending_pulse_errors{installation=\"$installation\"}"
    }
   ]
  },
  {
   "title": "Pulses generated / 10 sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(insolar_pulsar_pulse_generated{installation=\"$installation\"}[1m]) * 10"
    }
   ]
  }
 ]
}