{
 "title": "INS-Light Nodes",
 "tags": [ "INS" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "installation",
    "query": "label_values(insolar_light_last_sent_pulse, installation)"
   },
   {
    "name": "instance",
    "query": "label_values(insolar_light_last_sent_pulse{installation=\"$installation\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Current pulse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "repeat": "instance",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "insolar_current_pulse{instance=~\"$instance\", installation=\"$installation\"}"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "insolar_current_pulse{instance=~\"$instance\", installation=\"$installation\"}"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Index count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "insolar_object_indexes_added_count{instance=~\"$instance\", installation=\"$installation\"}-insolar_object_indexes_removed_count{instance=~\"$instance\", installation=\"$installation\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Records per pulse",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(insolar_drop_records_total{instance=~\"$instance\", installation=\"$installation\"}[1m])*10",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Opened request count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(insolar_requests_opened{instance=~\"$instance\", installation=\"$installation\"}-insolar_requests_closed{instance=~\"$instance\", installation=\"$installation\"})"
    }
   ]
  },
  {
   "title": "Jet count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "insolar_jets_counter{instance=~\"$instance\", installation=\"$installation\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Hot objects per pulse",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(insolar_hotdata_objects_send{instance=~\"$instance\", installation=\"$installation\"}[1m])*10",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Abandoned requests per pulse",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_requests_abandoned{instance=~\"$instance\", installation=\"$installation\"}[1m]))*10",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Heavy jet count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(insolar_jets_counter{instance=~\"$instance\", installation=\"$installation\"})",
     "legendFormat": "sum jets light"
    },
    { "expr": "insolar_heavy_jets_counter", "legendFormat": "heavy jets" }
   ]
  },
  {
   "title": "Filament records iterated per pulse",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(insolar_filament_length{instance=~\"$instance\", installation=\"$installation\"}[1m])*10",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Oldest abandoned request age",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "insolar_oldest_abandoned_request_age{installation=\"$installation\",instance=~\"$instance\"}",
     "legendFormat": "Oldest abandoned request age {{ instance }}"
    }
   ]
  },
  {
   "title": "Filament records fetched per pulse",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(insolar_filament_fetched_count{instance=~\"$instance\", installation=\"$installation\"}[1m])*10",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Set* stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "SetRequest Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_set_request_duplicate{instance=~\"$instance\", installation=\"$installation\"}[1m]))*10",
     "legendFormat": "SetRequest Duplicates"
    },
    {
     "expr": "sum(rate(insolar_set_request_total{instance=~\"$instance\", installation=\"$installation\"}[1m])-rate(insolar_set_request_success{instance=~\"$instance\", installation=\"$installation\"}[1m]))*10 -sum(rate(insolar_set_request_duplicate{instance=~\"$instance\", installation=\"$installation\"}[1m]))*10",
     "legendFormat": "Other SetRequest Errors"
    }
   ]
  },
  {
   "title": "SetResult errors per pulse",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_set_result_duplicate{instance=~\"$instance\", installation=\"$installation\"}[1m]))*10",
     "legendFormat": "SetResult duplicates"
    },
    {
     "expr": "sum(rate(insolar_set_result_total{instance=~\"$instance\", installation=\"$installation\"}[1m])-rate(insolar_set_result_success{instance=~\"$instance\", installation=\"$installation\"}[1m]))*10 -sum(rate(insolar_set_result_duplicate{instance=~\"$instance\", installation=\"$installation\"}[1m]))*10",
     "legendFormat": "Other SetResult errors"
    }
   ]
  }
 ]
}