{
 "title": "INS-Virtual",
 "time": { "from": "2019-09-12T13:24:20.671Z", "to": "2019-09-12T14:25:46.817Z" },
 "templating": {
  "list": [
   {
    "name": "installation",
    "query": "label_values(insolar_light_last_sent_pulse, installation)"
   }
  ]
 },
 "panels": [
  {
   "title": "VM Handle Future calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(insolar_vm_handle_future{installation=\"$installation\"}[1m])) by (vm_handle_payload_type)",
     "legendFormat": "{{vm_handle_payload_type}}"
    }
   ]
  },
  {
   "title": "VM Handle Past calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(insolar_vm_handle_past{installation=\"$installation\"}[1m])) by (vm_handle_payload_type)",
     "legendFormat": "{{vm_handle_payload_type}}"
    }
   ]
  },
  {
   "title": "VM Onpulse timing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(irate(insolar_vm_pulse_manager_onpulse_timing_sum{installation=\"$installation\"}[1m])) / sum(irate(insolar_vm_pulse_manager_onpulse_timing_count{installation=\"$installation\"}[1m]))",
     "legendFormat": "pulsemanager"
    },
    {
     "expr": "sum(irate(insolar_vm_logicrunner_onpulse_timing_sum{installation=\"$installation\"}[1m])) / sum(irate(insolar_vm_logicrunner_onpulse_timing_count{installation=\"$installation\"}[1m]))",
     "legendFormat": "logicrunner"
    },
    {
     "expr": "sum(irate(insolar_vm_execution_broker_onpulse_timing_sum{installation=\"$installation\"}[1m])) / sum(irate(insolar_vm_execution_broker_onpulse_timing_count{installation=\"$installation\"}[1m]))",
     "legendFormat": "executionbrokers"
    }
   ]
  },
  {
   "title": "VM Handle in progress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(insolar_vm_handle_started{installation=\"$installation\"}[1m])) by (vm_handle_payload_type) - sum(irate(insolar_vm_handle_finished{installation=\"$installation\"}[1m])) by (vm_handle_payload_type)",
     "legendFormat": "{{vm_handle_payload_type}}"
    }
   ]
  },
  {
   "title": "Virtual handles started",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(insolar_vm_handle_started{installation=\"$installation\"}[5m])) by (vm_handle_payload_type)",
     "legendFormat": "{{vm_handle_payload_type}}"
    }
   ]
  },
  {
   "title": "VM Handle finished with errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(insolar_vm_handle_finished{vm_handle_finished_with_error!=\"\", installation=\"$installation\"}[5m])) by (vm_handle_payload_type,vm_handle_finished_with_error)",
     "legendFormat": "{{vm_handle_payload_type}} , {{vm_handle_finished_with_error}}"
    }
   ]
  },
  {
   "title": "VM handling avg timing",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(irate(insolar_vm_handle_latency_sum{installation=\"$installation\"}[1m])) by (vm_handle_payload_type)/sum(irate(insolar_vm_handle_latency_count{installation=\"$installation\"}[1m])) by (vm_handle_payload_type)",
     "legendFormat": "{{vm_handle_payload_type}}"
    }
   ]
  },
  {
   "title": "ContractRequester RequestResults calls",
   "type": "graph",
   "description": "RequestResults handle",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(insolar_contract_requester_handle_started{installation=\"$installation\"}[5m])",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Contract Method avg timings",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(increase(insolar_vm_contracts_timing_sum{installation=\"$installation\"}[1m])) by (vm_execution_contract_method_name) / sum(increase(insolar_vm_contracts_timing_count{installation=\"$installation\"}[1m])) by (vm_execution_contract_method_name)",
     "legendFormat": "{{vm_execution_contract_method_name}}"
    }
   ]
  },
  {
   "title": "Outgoing Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(insolar_vm_outgoing_request_new{installation=\"$installation\"}[1m]))",
     "legendFormat": "new"
    },
    {
     "expr": "sum(irate(vm_outgoing_request_duplicate{installation=\"$installation\"}[1m]))",
     "legendFormat": "duplicates"
    },
    {
     "expr": "sum(irate(vm_outgoing_request_closed{installation=\"$installation\"}[1m]))",
     "legendFormat": "with results"
    }
   ]
  },
  {
   "title": "ContractRequester RequestResults handling errors",
   "type": "graph",
   "description": "RequestResults handle",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(insolar_contract_requester_handle_finished{role=\"virtual\",vm_handle_finished_with_error!=\"\", installation=\"$installation\"}[1m])) by (vm_handle_finished_with_error)",
     "legendFormat": "{{vm_handle_finished_with_error}}"
    }
   ]
  },
  {
   "title": "Incoming Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(insolar_vm_incoming_request_new{installation=\"$installation\"}[1m]))",
     "legendFormat": "new"
    },
    {
     "expr": "sum(irate(insolar_vm_outgoing_request_duplicate{installation=\"$installation\"}[1m]))",
     "legendFormat": "duplicates"
    },
    {
     "expr": "sum(irate(insolar_vm_outgoing_request_closed{installation=\"$installation\"}[1m]))",
     "legendFormat": "with results"
    }
   ]
  },
  {
   "title": "ExcecutionBroker Inflight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(insolar_vm_execution_broker_execution_started{installation=\"$installation\"}[1m])) - sum(irate(insolar_vm_execution_broker_execution_finished{installation=\"$installation\"}[1m]))"
    }
   ]
  },
  {
   "title": "Execution Broker processing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(insolar_vm_execution_broker_transcript_new{installation=\"$installation\"}[1m])) by (vm_execution_broker_queue_name)",
     "legendFormat": "new {{vm_execution_broker_queue_name}}"
    },
    {
     "expr": "sum(irate(vm_execution_broker_transcript_duplicate{installation=\"$installation\"}[1m])) by (vm_execution_broker_queue_name)",
     "legendFormat": "duplicates {{vm_execution_broker_queue_name}}"
    },
    {
     "expr": "sum(irate(vm_execution_broker_transcript_executing{installation=\"$installation\"}[1m])) by (vm_execution_broker_queue_name)",
     "legendFormat": "executing right now {{vm_execution_broker_queue_name}}"
    },
    {
     "expr": "sum(irate(vm_execution_broker_transcript_already_registered{installation=\"$installation\"}[1m])) by (vm_execution_broker_queue_name)",
     "legendFormat": "already registered {{vm_execution_broker_queue_name}}"
    }
   ]
  },
  {
   "title": "OutgoingSenderActorGoroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(insolar_vm_outgoing_sender_goroutines{installation=\"$installation\"}[1m]))",
     "legendFormat": "goroutines"
    }
   ]
  }
 ]
}