{
 "title": "INS-General",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Consensus Nodes On Heavy",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(insolar_consensus_active_nodes_count{instance=\"heavy-01.br20.insolar.io:8080\"})"
    }
   ]
  },
  {
   "title": "Errors In Logs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(insolar_log_calls{level=\"error\"})"
    }
   ]
  },
  {
   "title": "Pulse Number On Heavy",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "insolar_current_pulse{instance=\"heavy-01.br20.insolar.io:8080\"}"
    }
   ]
  },
  {
   "title": "VM Handle finished with errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(insolar_vm_handle_finished{vm_handle_finished_with_error!=\"\", installation=\"$installation\", instance=~\"$instance\"}[5m])) by (vm_handle_payload_type, vm_handle_finished_with_error, instance)",
     "legendFormat": "{{vm_handle_payload_type}}: {{instance}} \"{{vm_handle_finished_with_error}}\""
    }
   ]
  },
  {
   "title": "TPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(insolar_contract_requester_send_message_timing_count{role=\"virtual\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pulse deviation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(insolar_current_pulse{installation=\"prod\"}[60s])",
     "legendFormat": "P {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage, %",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"heavy-01.br20.insolar.io:9100\"}[5m])) by (host)) * 100",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"light-01.br20.insolar.io:9100\"}[5m])) by (host)) * 100",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"light-01.br20.insolar.io:9100\"}[5m])) by (host)) * 100",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"light-03.br20.insolar.io:9100\"}[5m])) by (host)) * 100",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"light-01.br20.insolar.io:9100\"}[5m])) by (host)) * 100",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"light-05.br20.insolar.io:9100\"}[5m])) by (host)) * 100",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"virtual-01.br20.insolar.io:9100\"}[5m])) by (host)) * 100",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"virtual-02.br20.insolar.io:9100\"}[5m])) by (host)) * 100",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"virtual-03.br20.insolar.io:9100\"}[5m])) by (host)) * 100",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"virtual-04.br20.insolar.io:9100\"}[5m])) by (host)) * 100",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"virtual-05.br20.insolar.io:9100\"}[5m])) by (host)) * 100",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory Usage, %",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "(1 - node_memory_MemAvailable_bytes{host=\"heavy-01.br20.insolar.io\"} / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes{host=\"light-01.br20.insolar.io\"} / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes{host=\"light-01.br20.insolar.io\"} / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes{host=\"light-03.br20.insolar.io\"} / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes{host=\"light-01.br20.insolar.io\"} / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes{host=\"light-05.br20.insolar.io\"} / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes{host=\"virtual-01.br20.insolar.io\"} / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes{host=\"virtual-02.br20.insolar.io\"} / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes{host=\"virtual-03.br20.insolar.io\"} / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes{host=\"virtual-03.br20.insolar.io\"} / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(1 - node_memory_MemAvailable_bytes{host=\"virtual-05.br20.insolar.io\"} / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk Usage, %",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "SUM(100 - ((node_filesystem_avail_bytes{instance=~\"heavy-01.br20.insolar.io:9100\",job=~\"node-exporter\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=~\"heavy-01.br20.insolar.io:9100\",job=~\"node-exporter\",device!~'rootfs'}))",
     "legendFormat": "heavy-01"
    },
    {
     "expr": "SUM(100 - ((node_filesystem_avail_bytes{instance=~\"light-01.br20.insolar.io:9100\",job=~\"node-exporter\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=~\"light-01.br20.insolar.io:9100\",job=~\"node-exporter\",device!~'rootfs'}))",
     "legendFormat": "light-01"
    },
    {
     "expr": "SUM(100 - ((node_filesystem_avail_bytes{instance=~\"light-02.br20.insolar.io:9100\",job=~\"node-exporter\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=~\"light-02.br20.insolar.io:9100\",job=~\"node-exporter\",device!~'rootfs'}))",
     "legendFormat": "light-02"
    },
    {
     "expr": "SUM(100 - ((node_filesystem_avail_bytes{instance=~\"light-03.br20.insolar.io:9100\",job=~\"node-exporter\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=~\"light-03.br20.insolar.io:9100\",job=~\"node-exporter\",device!~'rootfs'}))",
     "legendFormat": "light-03"
    },
    {
     "expr": "SUM(100 - ((node_filesystem_avail_bytes{instance=~\"light-04.br20.insolar.io:9100\",job=~\"node-exporter\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=~\"light-04.br20.insolar.io:9100\",job=~\"node-exporter\",device!~'rootfs'}))",
     "legendFormat": "light-04"
    },
    {
     "expr": "SUM(100 - ((node_filesystem_avail_bytes{instance=~\"light-05.br20.insolar.io:9100\",job=~\"node-exporter\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=~\"light-05.br20.insolar.io:9100\",job=~\"node-exporter\",device!~'rootfs'}))",
     "legendFormat": "light-05"
    },
    {
     "expr": "SUM(100 - ((node_filesystem_avail_bytes{instance=~\"virtual-01.br20.insolar.io:9100\",job=~\"node-exporter\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=~\"virtual-01.br20.insolar.io:9100\",job=~\"node-exporter\",device!~'rootfs'}))",
     "legendFormat": "virtual-01"
    },
    {
     "expr": "SUM(100 - ((node_filesystem_avail_bytes{instance=~\"virtual-02.br20.insolar.io:9100\",job=~\"node-exporter\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=~\"virtual-01.br20.insolar.io:9100\",job=~\"node-exporter\",device!~'rootfs'}))",
     "legendFormat": "virtual-02"
    },
    {
     "expr": "SUM(100 - ((node_filesystem_avail_bytes{instance=~\"virtual-03.br20.insolar.io:9100\",job=~\"node-exporter\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=~\"virtual-03.br20.insolar.io:9100\",job=~\"node-exporter\",device!~'rootfs'}))",
     "legendFormat": "virtual-03"
    },
    {
     "expr": "SUM(100 - ((node_filesystem_avail_bytes{instance=~\"virtual-04.br20.insolar.io:9100\",job=~\"node-exporter\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=~\"virtual-04.br20.insolar.io:9100\",job=~\"node-exporter\",device!~'rootfs'}))",
     "legendFormat": "virtual-04"
    },
    {
     "expr": "SUM(100 - ((node_filesystem_avail_bytes{instance=~\"virtual-05.br20.insolar.io:9100\",job=~\"node-exporter\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=~\"virtual-05.br20.insolar.io:9100\",job=~\"node-exporter\",device!~'rootfs'}))",
     "legendFormat": "virtual-05"
    }
   ]
  }
 ]
}