{
 "title": "INS-API",
 "tags": [ "INS" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "installation",
    "query": "label_values(insolar_api_incoming, installation)"
   },
   {
    "name": "instance",
    "query": "label_values(insolar_api_incoming, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "$instance",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "repeat": "instance",
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(insolar_api_incoming{instance=~\"$instance\"}[1m]))"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(insolar_api_incoming{instance=~\"$instance\"}[1m]))"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(insolar_api_incoming{instance=~\"$instance\"}[1m]))"
    }
   ]
  },
  { "title": "Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "\"ContractService\" finished requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_api_time_count{installation=~\"$installation\", instance=~\"$instance\", method=\"ContractService.call\"}[1m])) by (subMethod)",
     "legendFormat": "{{ subMethod }}"
    }
   ]
  },
  {
   "title": "\"AdminContractService\" finished requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_api_time_count{installation=~\"$installation\", instance=~\"$instance\", method=\"AdminContractService.call\"}[1m])) by (subMethod)",
     "legendFormat": "{{ subMethod }}"
    }
   ]
  },
  {
   "title": "\"Other\" finished requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_api_time_count{installation=~\"$installation\", instance=~\"$instance\", method!=\"ContractService.call\",method!=\"AdminContractService.call\"}[1m])) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_api_time_count{installation=~\"$installation\", instance=~\"$instance\", method=\"ContractService.call\", error!=\"\"}[1m]))",
     "legendFormat": "\"ContractService\" error rate"
    },
    {
     "expr": "sum(rate(insolar_api_time_count{installation=~\"$installation\", instance=~\"$instance\", method=\"AdminContractService.call\", error!=\"\"}[1m]))",
     "legendFormat": "\"AdminContractService\" error rate"
    },
    {
     "expr": "sum(rate(insolar_api_time_count{installation=~\"$installation\", instance=~\"$instance\", method!=\"ContractService.call\", method!=\"AdminContractService.call\", error!=\"\"}[1m]))",
     "legendFormat": "\"Other\" error rate"
    }
   ]
  },
  {
   "title": "\"ContractService\" execution time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "member.create execution time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(insolar_api_time_bucket{installation=~\"$installation\", instance=~\"$instance\", method=\"ContractService.call\", subMethod=\"member.create\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "member.get execution time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(insolar_api_time_bucket{installation=~\"$installation\", instance=~\"$instance\", method=\"ContractService.call\", subMethod=\"member.get\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "member.transfer execution time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(insolar_api_time_bucket{method=\"ContractService.call\", subMethod=\"member.transfer\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "member.migrationCreate execution time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 33 },
   "targets": [
    {
     "expr": "sum(increase(insolar_api_time_bucket{installation=~\"$installation\", instance=~\"$instance\", method=\"ContractService.call\", subMethod=\"member.migrationCreate\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "deposit.transfer execution time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(increase(insolar_api_time_bucket{installation=~\"$installation\", instance=~\"$instance\", method=\"ContractService.call\", subMethod=\"deposit.transfer\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "\"AdminContractService\" execution time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "migration.getInfo execution time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "sum(increase(insolar_api_time_bucket{installation=~\"$installation\", instance=~\"$instance\", method=\"AdminContractService.call\", subMethod=\"migration.getInfo\"}[1m])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "migration.deactivateDaemon execution time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 43 },
     "targets": [
      {
       "expr": "sum(increase(insolar_api_time_bucket{installation=~\"$installation\", instance=~\"$instance\", method=\"ContractService.call\", subMethod=\"migration.deactivateDaemon\"}[1m])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "migration.activateDaemon execution time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 43 },
     "targets": [
      {
       "expr": "sum(increase(insolar_api_time_bucket{installation=~\"$installation\", instance=~\"$instance\", method=\"AdminContractService.call\", subMethod=\"migration.activateDaemon\"}[1m])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "migration.checkDaemon execution time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "sum(increase(insolar_api_time_bucket{installation=~\"$installation\", instance=~\"$instance\", method=\"AdminContractService.call\", subMethod=\"migration.checkDaemon\"}[1m])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "migration.addAddresses execution time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 52 },
     "targets": [
      {
       "expr": "sum(increase(insolar_api_time_bucket{installation=~\"$installation\", instance=~\"$instance\", method=\"AdminContractService.call\", subMethod=\"migration.addAddresses\"}[1m])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "deposit.migration execution time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 52 },
     "targets": [
      {
       "expr": "sum(increase(insolar_api_time_bucket{installation=~\"$installation\", instance=~\"$instance\", method=\"AdminContractService.call\", subMethod=\"deposit.migration\"}[1m])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "member.getBalance execution time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "sum(increase(insolar_api_time_bucket{installation=~\"$installation\", instance=~\"$instance\", method=\"AdminContractService.call\", subMethod=\"member.getBalance\"}[1m])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "contract.registerNode execution time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 61 },
     "targets": [
      {
       "expr": "sum(increase(insolar_api_time_bucket{installation=~\"$installation\", instance=~\"$instance\", method=\"AdminContractService.call\", subMethod=\"contract.registerNode\"}[1m])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "contract.getNodeRef execution time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 61 },
     "targets": [
      {
       "expr": "sum(increase(insolar_api_time_bucket{installation=~\"$installation\", instance=~\"$instance\", method=\"AdminContractService.call\", subMethod=\"contract.getNodeRef\"}[1m])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  {
   "title": "\"Other\" execution time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeService.getSeed execution time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "sum(increase(insolar_api_time_bucket{installation=~\"$installation\", instance=~\"$instance\", method=\"NodeService.getSeed\"}[1m])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "NodeCertService.get execution time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 71 },
     "targets": [
      {
       "expr": "sum(increase(insolar_api_time_bucket{installation=~\"$installation\", instance=~\"$instance\", method=\"NodeCertService.get\"}[1m])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "InfoService.getInfo execution time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 71 },
     "targets": [
      {
       "expr": "sum(increase(insolar_api_time_bucket{installation=~\"$installation\", instance=~\"$instance\", method=\"InfoService.getInfo\"}[1m])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  }
 ]
}