{
 "title": "INS-Bus",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "type",
    "label": "message type",
    "query": "label_values(insolar_bus_sent_total, message_type)"
   },
   {
    "name": "instance",
    "query": "label_values(insolar_bus_sent_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Reply latency \"$type\" ($instance)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(insolar_bus_reply_milliseconds_bucket{message_type=~\"$type\", instance=~\"$instance\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Average size \"$type\" ($instance)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_bus_sent_bytes_sum{message_type=~\"$type\", instance=~\"$instance\"}[1m])) / sum(rate(insolar_bus_sent_bytes_count{message_type=~\"$type\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "Size (bytes) / sec"
    }
   ]
  },
  {
   "title": "Retries \"$type\" ($instance)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_bus_sent_retries{message_type=~\"$type\",instance=~\"$instance\"}[1m])) by (job)",
     "legendFormat": "count / sec"
    }
   ]
  },
  {
   "title": "Sizes \"$type\" ($instance)",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(insolar_bus_sent_bytes_bucket{message_type=~\"$type\", instance=~\"$instance\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Replies \"$type\" ($instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_bus_reply_total{instance=~\"$instance\",message_type=~\"$type\"}[1m]))",
     "legendFormat": "count / sec"
    }
   ]
  },
  {
   "title": "Total reply timeouts ($instance)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_bus_reply_timeouts{instance=~\"$instance\",message_type=~\"$type\"}[1m]))",
     "legendFormat": "per minute"
    }
   ]
  },
  {
   "title": "Messages \"$type\" sent ($instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_bus_sent_total{instance=~\"$instance\",message_type=~\"$type\"}[1m]))",
     "legendFormat": "count / sec"
    }
   ]
  },
  {
   "title": "Send latency \"$type\" ($instance)",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(insolar_bus_sent_milliseconds_bucket{message_type=~\"$type\", instance=~\"$instance\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}