{
 "title": "INS GO metrics",
 "tags": [ "INS" ],
 "time": { "from": "now-1d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(insolar_process_max_fds, instance)"
   },
   {
    "name": "role",
    "query": "label_values(insolar_process_max_fds, role)"
   }
  ]
 },
 "panels": [
  { "title": "Go", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(insolar_process_cpu_seconds_total{role=~\"$role\", instance=~\"$node\"}[1m])",
     "legendFormat": "{{job}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$node\", role=~\"$role\"}",
     "legendFormat": "{{job}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{role=~\"$role\", instance=~\"$node\"}",
     "legendFormat": "{{job}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Heap GC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_gc_sys_bytes{role=~\"$role\", instance=~\"$node\"}[1m]) ",
     "legendFormat": "{{job}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{role=~\"$role\", instance=~\"$node\"}"
    }
   ]
  }
 ]
}