{
 "title": "INS-Logging",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "installation",
    "query": "label_values(insolar_light_last_sent_pulse, installation)"
   }
  ]
 },
 "panels": [
  {
   "title": "Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(insolar_log_calls{level=\"error\", installation=$installation})"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(insolar_log_calls{level=\"warn\", installation=$installation})"
    }
   ]
  },
  {
   "title": "Infos",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(insolar_log_calls{level=\"info\", installation=$installation})"
    }
   ]
  },
  {
   "title": "Logs call rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_log_calls{installation=$installation}[1m]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Logs write rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_log_written{installation=$installation}[1m]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Written log 1m rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_log_written{installation=$installation}[1m])) by (level)",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "Calls 1m rate by role",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_log_calls{installation=$installation}[1m])) by (level, role)",
     "legendFormat": "{{ level }}: {{ role }}"
    }
   ]
  }
 ]
}