{
 "title": "Light Material Nodes",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(insolar_light_last_sent_pulse, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Current pulse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "repeat": "instance",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "insolar_current_pulse{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "insolar_current_pulse{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Last synced pulse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "$instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 4 },
   "repeat": "instance",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "insolar_light_last_sent_pulse{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "insolar_light_last_sent_pulse{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "requests rate ($instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_requests_opened{instance=~\"$instance\"}[1m]))",
     "legendFormat": "opened"
    },
    {
     "expr": "sum(rate(insolar_requests_closed{instance=~\"$instance\"}[1m]))",
     "legendFormat": "closed"
    }
   ]
  },
  {
   "title": "send hot objects rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_hotdata_objects_send{instance=~\"$instance\"}[1m]))"
    }
   ]
  },
  {
   "title": "abandoned ($instance)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(insolar_requests_abandoned{instance=~\"$instance\"} - insolar_requests_abandoned{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "opened - closed ($instance)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(insolar_requests_opened{instance=~\"$instance\"} - insolar_requests_closed{instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Buckets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_object_indexes_added_count{instance=~\"$instance\"}[1m]))",
     "legendFormat": "added"
    },
    {
     "expr": "sum(rate(insolar_object_indexes_removed_count{instance=~\"$instance\"}[1m]))",
     "legendFormat": "removed"
    }
   ]
  },
  {
   "title": "Avg records count per drop",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(insolar_drop_records_total{instance=~\"$instance\"}/insolar_drops_total{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Drop storage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_dropstorage_added_count{instance=~\"$instance\"}[1m]))",
     "legendFormat": "added"
    },
    {
     "expr": "sum(rate(insolar_dropstorage_removed_count{instance=~\"$instance\"}[1m]))",
     "legendFormat": "removed"
    }
   ]
  },
  {
   "title": "Jets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(insolar_jets_counter{instance=~\"$instance\"})",
     "legendFormat": "sum jets light"
    },
    { "expr": "insolar_heavy_jets_counter", "legendFormat": "heavy jets" }
   ]
  }
 ]
}