{
 "title": "LM storage",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "removed and scanned",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(insolard_lightcleanup_removed[5m])) by (rectype)",
     "legendFormat": "removed {{ rectype }}"
    },
    {
     "expr": "sum(increase(insolard_lightcleanup_scanned[5m])) by (rectype)",
     "legendFormat": "scanned {{ rectype }}"
    }
   ]
  },
  {
   "title": "remove/scans < 1",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(insolard_lightcleanup_removed[5m])) by (rectype)  / sum(increase(insolard_lightcleanup_scanned[5m])) by (rectype) < 1",
     "legendFormat": "{{ rectype }}"
    }
   ]
  },
  {
   "title": "recent storage: objects",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(insolard_storage_recent_objects_added_count[1m]))",
     "legendFormat": "added"
    },
    {
     "expr": "sum(increase(insolard_storage_recent_objects_removed_count[1m]))",
     "legendFormat": "removed"
    }
   ]
  },
  {
   "title": "DB cleanup latency",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by(le) (increase(insolard_lightcleanup_latency_db_bucket[1m]))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Total cleanup latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(increase(insolard_lightcleanup_latency_total_bucket[1m])) by (le))",
     "legendFormat": "0.999"
    },
    {
     "expr": "histogram_quantile(0.9, sum(increase(insolard_lightcleanup_latency_total_bucket[1m])) by (le))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum(increase(insolard_lightcleanup_latency_total_bucket[1m])) by (le))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Unique Jets in heavy metrics",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count by (jet) (insolard_heavyserver_synced_bytes))"
    }
   ]
  }
 ]
}