{
 "title": "INS-Light Nodes test",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(insolar_light_last_sent_pulse, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Current pulse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "repeat": "instance",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "insolar_current_pulse{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "insolar_current_pulse{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "insolar_current_pulse{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "insolar_current_pulse{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "insolar_current_pulse{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Index count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "insolar_object_indexes_added_count{instance=~\"$instance\"}-insolar_object_indexes_removed_count{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Records per pulse",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(insolar_drop_records_total{instance=~\"$instance\"}[1m])*10",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Opened request count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(insolar_requests_opened{instance=~\"$instance\"}-insolar_requests_closed{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Jet count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "insolar_jets_counter{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Hot objects per pulse",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(insolar_hotdata_objects_send{instance=~\"$instance\"}[1m])*10",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Abandoned requests per pulse",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(insolar_requests_abandoned{instance=~\"$instance\"}[1m]))*10",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Heavy jet count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(insolar_jets_counter{instance=~\"$instance\"})",
     "legendFormat": "sum jets light"
    },
    { "expr": "insolar_heavy_jets_counter", "legendFormat": "heavy jets" }
   ]
  }
 ]
}