{
 "title": "Insolar Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "installation",
    "query": "label_values(insolar_light_last_sent_pulse, installation)"
   }
  ]
 },
 "panels": [
  {
   "title": "AM Latency (0.95)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, insolard_artifactmanager_latency_bucket{installation=$installation})"
    }
   ]
  },
  {
   "title": "AM Latency (0.99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, insolard_artifactmanager_latency_bucket{installation=$installation})"
    }
   ]
  },
  {
   "title": "GO GC (sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds_sum{installation=$installation} / go_gc_duration_seconds_count{installation=$installation} "
    }
   ]
  },
  {
   "title": "Go Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{installation=$installation}"
    }
   ]
  },
  {
   "title": "Go Heap Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_sys_bytes{installation=$installation}"
    }
   ]
  },
  {
   "title": "Go Alloc Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes_total{installation=$installation} "
    }
   ]
  },
  {
   "title": "Go Frees Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_frees_total{installation=$installation}"
    }
   ]
  },
  {
   "title": "Go Heap Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_objects{installation=$installation}"
    }
   ]
  }
 ]
}