run:
  tests: false
  skip-dirs:
    - application/contract/
    - application/proxy/

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - gas
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - golint
    - staticcheck
