run:
  tests: false
  skip-dirs:
    - application/contract/
    - application/proxy/
    - logicrunner/goplugin/ginsider/healthcheck

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - gosec
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - golint
    - interfacer
    - unconvert
    - goconst
    - misspell
    - unparam
    - nakedret
    - prealloc
    - scopelint
    - gocritic

linters-settings:
  goimports:
    local-prefixes: github.com/insolar/insolar

issues:
  exclude-rules:
    - text: "S1021:"
      linters:
        - gosimple
