#!/usr/bin/env bash
read -r -d '' help <<'EOF'
#
# Helper for searching inside launchnet nodes logs
#
# Usage:
#
# ./insolar-scripts/glogs "PATTERN" [grep flags]
#
# Examples:
#
# ./insolar-scripts/glogs "synchronize" -C1
#
# force grep usage:
#
# USE_GREP=1 ./insolar-scripts/glogs "panic|error" -E -A10
#
EOF

if [[ $# -lt 1 ]]; then
    echo "Error: wrong usage"
    echo "$help"
    exit 1
fi

INSOLAR_ARTIFACTS_DIR=${INSOLAR_ARTIFACTS_DIR:-".artifacts"}/
LAUNCHNET_BASE_DIR=${LAUNCHNET_BASE_DIR:-"${INSOLAR_ARTIFACTS_DIR}launchnet"}/

USE_GREP=${USE_GREP:-"0"}
USE_AG=${USE_AG:-"0"}

AG_BIN=$(which ag)

SEARCH_PATTERN=$1
shift

if [[ "${AG_BIN}" != "" && ${USE_GREP} != "1" ]]; then
    set -x
    ag $@ "$SEARCH_PATTERN" ${LAUNCHNET_BASE_DIR}logs/*nodes/*/output.log
    { set +x; } 2>/dev/null
else
    set -x
    grep $@ "$SEARCH_PATTERN" ${LAUNCHNET_BASE_DIR}logs/*nodes/*/output.log
    { set +x; } 2>/dev/null
fi
