#!/usr/bin/env bash
read -r -d '' help <<'EOF'
#
# Helper for tailing launchnet logs
#
# Usage:
#
# ./insolar-scripts/tails [tail flags]
##
EOF

INSOLAR_ARTIFACTS_DIR=${INSOLAR_ARTIFACTS_DIR:-".artifacts"}/
LAUNCHNET_BASE_DIR=${LAUNCHNET_BASE_DIR:-"${INSOLAR_ARTIFACTS_DIR}launchnet"}/

set -x
tail $@ ${LAUNCHNET_BASE_DIR}logs/*nodes/*/output.log
