global:
  scrape_interval: 5s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'node-1'
    static_configs:
      - targets: ['host.docker.internal:8081']
  - job_name: 'node-2'
    static_configs:
      - targets: ['host.docker.internal:8082']
  - job_name: 'node-3'
    static_configs:
      - targets: ['host.docker.internal:8083']
  - job_name: 'node-4'
    static_configs:
      - targets: ['host.docker.internal:8084']
  - job_name: 'node-5'
    static_configs:
      - targets: ['host.docker.internal:8085']