FROM golang:1.11

RUN mkdir -p /go/src/github.com/insolar/insolar
ADD . /go/src/github.com/insolar/insolar
WORKDIR /go/src/github.com/insolar/insolar

ENV BIN_DIR="/go/bin"
ENV CGO_ENABLED=1
ENV GOOS=linux

RUN make install-deps pre-build build
EXPOSE 8080
EXPOSE 19191
ENTRYPOINT ["/go/bin/insolard"]
