// Code generated by "stringer -type=DelegationTokenType"; DO NOT EDIT.

package core

import "strconv"

const _DelegationTokenType_name = "DTTypePendingExecution"

var _DelegationTokenType_index = [...]uint8{0, 22}

func (i DelegationTokenType) String() string {
	if i >= DelegationTokenType(len(_DelegationTokenType_index)-1) {
		return "DelegationTokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DelegationTokenType_name[_DelegationTokenType_index[i]:_DelegationTokenType_index[i+1]]
}
