// Code generated by "stringer -type=DelegationTokenType"; DO NOT EDIT.

package core

import "strconv"

const _DelegationTokenType_name = "DTTypePendingExecutionDTTypeGetObjectRedirectDTTypeGetChildrenRedirectDTTypeGetCodeRedirect"

var _DelegationTokenType_index = [...]uint8{0, 22, 45, 70, 91}

func (i DelegationTokenType) String() string {
	i -= 1
	if i >= DelegationTokenType(len(_DelegationTokenType_index)-1) {
		return "DelegationTokenType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _DelegationTokenType_name[_DelegationTokenType_index[i]:_DelegationTokenType_index[i+1]]
}
