// Code generated by "stringer -type=Type"; DO NOT EDIT.

package payload

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeUnknown-0]
	_ = x[TypeMeta-1]
	_ = x[TypeError-2]
	_ = x[TypeID-3]
	_ = x[TypeIDs-4]
	_ = x[TypeState-5]
	_ = x[TypeGetObject-6]
	_ = x[TypePassState-7]
	_ = x[TypeObjIndex-8]
	_ = x[TypeObjState-9]
	_ = x[TypeIndex-10]
	_ = x[TypePass-11]
	_ = x[TypeGetCode-12]
	_ = x[TypeCode-13]
	_ = x[TypeSetCode-14]
	_ = x[TypeSetIncomingRequest-15]
	_ = x[TypeSetOutgoingRequest-16]
	_ = x[TypeSagaCallAcceptNotification-17]
	_ = x[TypeGetFilament-18]
	_ = x[TypeGetRequest-19]
	_ = x[TypeRequest-20]
	_ = x[TypeFilamentSegment-21]
	_ = x[TypeSetResult-22]
	_ = x[TypeActivate-23]
	_ = x[TypeRequestInfo-24]
	_ = x[TypeGotHotConfirmation-25]
	_ = x[TypeDeactivate-26]
	_ = x[TypeUpdate-27]
	_ = x[TypeHotObjects-28]
	_ = x[TypeResultInfo-29]
	_ = x[TypeGetPendings-30]
	_ = x[TypeReplication-31]
	_ = x[TypeReturnResults-32]
	_ = x[TypeCallMethod-33]
	_ = x[TypeExecutorResults-34]
	_ = x[TypePendingFinished-35]
	_ = x[TypeAdditionalCallFromPreviousExecutor-36]
	_ = x[TypeStillExecuting-37]
	_ = x[_latestType-38]
}

const _Type_name = "TypeUnknownTypeMetaTypeErrorTypeIDTypeIDsTypeStateTypeGetObjectTypePassStateTypeObjIndexTypeObjStateTypeIndexTypePassTypeGetCodeTypeCodeTypeSetCodeTypeSetIncomingRequestTypeSetOutgoingRequestTypeSagaCallAcceptNotificationTypeGetFilamentTypeGetRequestTypeRequestTypeFilamentSegmentTypeSetResultTypeActivateTypeRequestInfoTypeGotHotConfirmationTypeDeactivateTypeUpdateTypeHotObjectsTypeResultInfoTypeGetPendingsTypeReplicationTypeReturnResultsTypeCallMethodTypeExecutorResultsTypePendingFinishedTypeAdditionalCallFromPreviousExecutorTypeStillExecuting_latestType"

var _Type_index = [...]uint16{0, 11, 19, 28, 34, 41, 50, 63, 76, 88, 100, 109, 117, 128, 136, 147, 169, 191, 221, 236, 250, 261, 280, 293, 305, 320, 342, 356, 366, 380, 394, 409, 424, 441, 455, 474, 493, 531, 549, 560}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
