#!/usr/bin/env bash
read -r -d '' help <<'EOF'
#
# Helper for searching inside launchnet nodes logs
#
# Usage:
#
# ./scripts/glogs "PATTERN" [grep flags]
#
# Examples:
#
# ./scripts/glogs "synchronize" -C1
#
# ./scripts/glogs "panic|error" -E -A10
#
EOF
 echo '"$#" =' "$#"
if [[ $# -lt 1 ]]; then
    echo "Error: wrong usage"
    echo "$help"
    exit 1
fi

INSOLAR_ARTIFACTS_DIR=${INSOLAR_ARTIFACTS_DIR:-".artifacts"}/
LAUNCHNET_BASE_DIR=${LAUNCHNET_BASE_DIR:-"${INSOLAR_ARTIFACTS_DIR}launchnet"}/

SEARCH_PATTERN=$1
shift


#grep $@ "$SEARCH_PATTERN" ${LAUNCHNET_BASE_DIR}logs/discoverynodes/*/output.log

if which ag ; then
    set -x
    ag $@ "$SEARCH_PATTERN" ${LAUNCHNET_BASE_DIR}logs/discoverynodes/*/output.log
    { set +x; } 2>/dev/null
else
    set -x
    grep $@ "$SEARCH_PATTERN" ${LAUNCHNET_BASE_DIR}logs/discoverynodes/*/output.log
    { set +x; } 2>/dev/null
fi
