package requestsfetcher

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock"
)

// RequestsFetcherMock implements RequestsFetcher
type RequestsFetcherMock struct {
	t minimock.Tester

	funcAbort          func(ctx context.Context)
	inspectFuncAbort   func(ctx context.Context)
	afterAbortCounter  uint64
	beforeAbortCounter uint64
	AbortMock          mRequestsFetcherMockAbort

	funcFetchPendings          func(ctx context.Context)
	inspectFuncFetchPendings   func(ctx context.Context)
	afterFetchPendingsCounter  uint64
	beforeFetchPendingsCounter uint64
	FetchPendingsMock          mRequestsFetcherMockFetchPendings
}

// NewRequestsFetcherMock returns a mock for RequestsFetcher
func NewRequestsFetcherMock(t minimock.Tester) *RequestsFetcherMock {
	m := &RequestsFetcherMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AbortMock = mRequestsFetcherMockAbort{mock: m}
	m.AbortMock.callArgs = []*RequestsFetcherMockAbortParams{}

	m.FetchPendingsMock = mRequestsFetcherMockFetchPendings{mock: m}
	m.FetchPendingsMock.callArgs = []*RequestsFetcherMockFetchPendingsParams{}

	return m
}

type mRequestsFetcherMockAbort struct {
	mock               *RequestsFetcherMock
	defaultExpectation *RequestsFetcherMockAbortExpectation
	expectations       []*RequestsFetcherMockAbortExpectation

	callArgs []*RequestsFetcherMockAbortParams
	mutex    sync.RWMutex
}

// RequestsFetcherMockAbortExpectation specifies expectation struct of the RequestsFetcher.Abort
type RequestsFetcherMockAbortExpectation struct {
	mock   *RequestsFetcherMock
	params *RequestsFetcherMockAbortParams

	Counter uint64
}

// RequestsFetcherMockAbortParams contains parameters of the RequestsFetcher.Abort
type RequestsFetcherMockAbortParams struct {
	ctx context.Context
}

// Expect sets up expected params for RequestsFetcher.Abort
func (mmAbort *mRequestsFetcherMockAbort) Expect(ctx context.Context) *mRequestsFetcherMockAbort {
	if mmAbort.mock.funcAbort != nil {
		mmAbort.mock.t.Fatalf("RequestsFetcherMock.Abort mock is already set by Set")
	}

	if mmAbort.defaultExpectation == nil {
		mmAbort.defaultExpectation = &RequestsFetcherMockAbortExpectation{}
	}

	mmAbort.defaultExpectation.params = &RequestsFetcherMockAbortParams{ctx}
	for _, e := range mmAbort.expectations {
		if minimock.Equal(e.params, mmAbort.defaultExpectation.params) {
			mmAbort.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAbort.defaultExpectation.params)
		}
	}

	return mmAbort
}

// Inspect accepts an inspector function that has same arguments as the RequestsFetcher.Abort
func (mmAbort *mRequestsFetcherMockAbort) Inspect(f func(ctx context.Context)) *mRequestsFetcherMockAbort {
	if mmAbort.mock.inspectFuncAbort != nil {
		mmAbort.mock.t.Fatalf("Inspect function is already set for RequestsFetcherMock.Abort")
	}

	mmAbort.mock.inspectFuncAbort = f

	return mmAbort
}

// Return sets up results that will be returned by RequestsFetcher.Abort
func (mmAbort *mRequestsFetcherMockAbort) Return() *RequestsFetcherMock {
	if mmAbort.mock.funcAbort != nil {
		mmAbort.mock.t.Fatalf("RequestsFetcherMock.Abort mock is already set by Set")
	}

	if mmAbort.defaultExpectation == nil {
		mmAbort.defaultExpectation = &RequestsFetcherMockAbortExpectation{mock: mmAbort.mock}
	}

	return mmAbort.mock
}

//Set uses given function f to mock the RequestsFetcher.Abort method
func (mmAbort *mRequestsFetcherMockAbort) Set(f func(ctx context.Context)) *RequestsFetcherMock {
	if mmAbort.defaultExpectation != nil {
		mmAbort.mock.t.Fatalf("Default expectation is already set for the RequestsFetcher.Abort method")
	}

	if len(mmAbort.expectations) > 0 {
		mmAbort.mock.t.Fatalf("Some expectations are already set for the RequestsFetcher.Abort method")
	}

	mmAbort.mock.funcAbort = f
	return mmAbort.mock
}

// Abort implements RequestsFetcher
func (mmAbort *RequestsFetcherMock) Abort(ctx context.Context) {
	mm_atomic.AddUint64(&mmAbort.beforeAbortCounter, 1)
	defer mm_atomic.AddUint64(&mmAbort.afterAbortCounter, 1)

	if mmAbort.inspectFuncAbort != nil {
		mmAbort.inspectFuncAbort(ctx)
	}

	params := &RequestsFetcherMockAbortParams{ctx}

	// Record call args
	mmAbort.AbortMock.mutex.Lock()
	mmAbort.AbortMock.callArgs = append(mmAbort.AbortMock.callArgs, params)
	mmAbort.AbortMock.mutex.Unlock()

	for _, e := range mmAbort.AbortMock.expectations {
		if minimock.Equal(e.params, params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return
		}
	}

	if mmAbort.AbortMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAbort.AbortMock.defaultExpectation.Counter, 1)
		want := mmAbort.AbortMock.defaultExpectation.params
		got := RequestsFetcherMockAbortParams{ctx}
		if want != nil && !minimock.Equal(*want, got) {
			mmAbort.t.Errorf("RequestsFetcherMock.Abort got unexpected parameters, want: %#v, got: %#v%s\n", *want, got, minimock.Diff(*want, got))
		}

		return

	}
	if mmAbort.funcAbort != nil {
		mmAbort.funcAbort(ctx)
		return
	}
	mmAbort.t.Fatalf("Unexpected call to RequestsFetcherMock.Abort. %v", ctx)

}

// AbortAfterCounter returns a count of finished RequestsFetcherMock.Abort invocations
func (mmAbort *RequestsFetcherMock) AbortAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAbort.afterAbortCounter)
}

// AbortBeforeCounter returns a count of RequestsFetcherMock.Abort invocations
func (mmAbort *RequestsFetcherMock) AbortBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAbort.beforeAbortCounter)
}

// Calls returns a list of arguments used in each call to RequestsFetcherMock.Abort.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAbort *mRequestsFetcherMockAbort) Calls() []*RequestsFetcherMockAbortParams {
	mmAbort.mutex.RLock()

	argCopy := make([]*RequestsFetcherMockAbortParams, len(mmAbort.callArgs))
	copy(argCopy, mmAbort.callArgs)

	mmAbort.mutex.RUnlock()

	return argCopy
}

// MinimockAbortDone returns true if the count of the Abort invocations corresponds
// the number of defined expectations
func (m *RequestsFetcherMock) MinimockAbortDone() bool {
	for _, e := range m.AbortMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.AbortMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterAbortCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAbort != nil && mm_atomic.LoadUint64(&m.afterAbortCounter) < 1 {
		return false
	}
	return true
}

// MinimockAbortInspect logs each unmet expectation
func (m *RequestsFetcherMock) MinimockAbortInspect() {
	for _, e := range m.AbortMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RequestsFetcherMock.Abort with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.AbortMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterAbortCounter) < 1 {
		if m.AbortMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to RequestsFetcherMock.Abort")
		} else {
			m.t.Errorf("Expected call to RequestsFetcherMock.Abort with params: %#v", *m.AbortMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAbort != nil && mm_atomic.LoadUint64(&m.afterAbortCounter) < 1 {
		m.t.Error("Expected call to RequestsFetcherMock.Abort")
	}
}

type mRequestsFetcherMockFetchPendings struct {
	mock               *RequestsFetcherMock
	defaultExpectation *RequestsFetcherMockFetchPendingsExpectation
	expectations       []*RequestsFetcherMockFetchPendingsExpectation

	callArgs []*RequestsFetcherMockFetchPendingsParams
	mutex    sync.RWMutex
}

// RequestsFetcherMockFetchPendingsExpectation specifies expectation struct of the RequestsFetcher.FetchPendings
type RequestsFetcherMockFetchPendingsExpectation struct {
	mock   *RequestsFetcherMock
	params *RequestsFetcherMockFetchPendingsParams

	Counter uint64
}

// RequestsFetcherMockFetchPendingsParams contains parameters of the RequestsFetcher.FetchPendings
type RequestsFetcherMockFetchPendingsParams struct {
	ctx context.Context
}

// Expect sets up expected params for RequestsFetcher.FetchPendings
func (mmFetchPendings *mRequestsFetcherMockFetchPendings) Expect(ctx context.Context) *mRequestsFetcherMockFetchPendings {
	if mmFetchPendings.mock.funcFetchPendings != nil {
		mmFetchPendings.mock.t.Fatalf("RequestsFetcherMock.FetchPendings mock is already set by Set")
	}

	if mmFetchPendings.defaultExpectation == nil {
		mmFetchPendings.defaultExpectation = &RequestsFetcherMockFetchPendingsExpectation{}
	}

	mmFetchPendings.defaultExpectation.params = &RequestsFetcherMockFetchPendingsParams{ctx}
	for _, e := range mmFetchPendings.expectations {
		if minimock.Equal(e.params, mmFetchPendings.defaultExpectation.params) {
			mmFetchPendings.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmFetchPendings.defaultExpectation.params)
		}
	}

	return mmFetchPendings
}

// Inspect accepts an inspector function that has same arguments as the RequestsFetcher.FetchPendings
func (mmFetchPendings *mRequestsFetcherMockFetchPendings) Inspect(f func(ctx context.Context)) *mRequestsFetcherMockFetchPendings {
	if mmFetchPendings.mock.inspectFuncFetchPendings != nil {
		mmFetchPendings.mock.t.Fatalf("Inspect function is already set for RequestsFetcherMock.FetchPendings")
	}

	mmFetchPendings.mock.inspectFuncFetchPendings = f

	return mmFetchPendings
}

// Return sets up results that will be returned by RequestsFetcher.FetchPendings
func (mmFetchPendings *mRequestsFetcherMockFetchPendings) Return() *RequestsFetcherMock {
	if mmFetchPendings.mock.funcFetchPendings != nil {
		mmFetchPendings.mock.t.Fatalf("RequestsFetcherMock.FetchPendings mock is already set by Set")
	}

	if mmFetchPendings.defaultExpectation == nil {
		mmFetchPendings.defaultExpectation = &RequestsFetcherMockFetchPendingsExpectation{mock: mmFetchPendings.mock}
	}

	return mmFetchPendings.mock
}

//Set uses given function f to mock the RequestsFetcher.FetchPendings method
func (mmFetchPendings *mRequestsFetcherMockFetchPendings) Set(f func(ctx context.Context)) *RequestsFetcherMock {
	if mmFetchPendings.defaultExpectation != nil {
		mmFetchPendings.mock.t.Fatalf("Default expectation is already set for the RequestsFetcher.FetchPendings method")
	}

	if len(mmFetchPendings.expectations) > 0 {
		mmFetchPendings.mock.t.Fatalf("Some expectations are already set for the RequestsFetcher.FetchPendings method")
	}

	mmFetchPendings.mock.funcFetchPendings = f
	return mmFetchPendings.mock
}

// FetchPendings implements RequestsFetcher
func (mmFetchPendings *RequestsFetcherMock) FetchPendings(ctx context.Context) {
	mm_atomic.AddUint64(&mmFetchPendings.beforeFetchPendingsCounter, 1)
	defer mm_atomic.AddUint64(&mmFetchPendings.afterFetchPendingsCounter, 1)

	if mmFetchPendings.inspectFuncFetchPendings != nil {
		mmFetchPendings.inspectFuncFetchPendings(ctx)
	}

	params := &RequestsFetcherMockFetchPendingsParams{ctx}

	// Record call args
	mmFetchPendings.FetchPendingsMock.mutex.Lock()
	mmFetchPendings.FetchPendingsMock.callArgs = append(mmFetchPendings.FetchPendingsMock.callArgs, params)
	mmFetchPendings.FetchPendingsMock.mutex.Unlock()

	for _, e := range mmFetchPendings.FetchPendingsMock.expectations {
		if minimock.Equal(e.params, params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return
		}
	}

	if mmFetchPendings.FetchPendingsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmFetchPendings.FetchPendingsMock.defaultExpectation.Counter, 1)
		want := mmFetchPendings.FetchPendingsMock.defaultExpectation.params
		got := RequestsFetcherMockFetchPendingsParams{ctx}
		if want != nil && !minimock.Equal(*want, got) {
			mmFetchPendings.t.Errorf("RequestsFetcherMock.FetchPendings got unexpected parameters, want: %#v, got: %#v%s\n", *want, got, minimock.Diff(*want, got))
		}

		return

	}
	if mmFetchPendings.funcFetchPendings != nil {
		mmFetchPendings.funcFetchPendings(ctx)
		return
	}
	mmFetchPendings.t.Fatalf("Unexpected call to RequestsFetcherMock.FetchPendings. %v", ctx)

}

// FetchPendingsAfterCounter returns a count of finished RequestsFetcherMock.FetchPendings invocations
func (mmFetchPendings *RequestsFetcherMock) FetchPendingsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmFetchPendings.afterFetchPendingsCounter)
}

// FetchPendingsBeforeCounter returns a count of RequestsFetcherMock.FetchPendings invocations
func (mmFetchPendings *RequestsFetcherMock) FetchPendingsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmFetchPendings.beforeFetchPendingsCounter)
}

// Calls returns a list of arguments used in each call to RequestsFetcherMock.FetchPendings.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmFetchPendings *mRequestsFetcherMockFetchPendings) Calls() []*RequestsFetcherMockFetchPendingsParams {
	mmFetchPendings.mutex.RLock()

	argCopy := make([]*RequestsFetcherMockFetchPendingsParams, len(mmFetchPendings.callArgs))
	copy(argCopy, mmFetchPendings.callArgs)

	mmFetchPendings.mutex.RUnlock()

	return argCopy
}

// MinimockFetchPendingsDone returns true if the count of the FetchPendings invocations corresponds
// the number of defined expectations
func (m *RequestsFetcherMock) MinimockFetchPendingsDone() bool {
	for _, e := range m.FetchPendingsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.FetchPendingsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterFetchPendingsCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcFetchPendings != nil && mm_atomic.LoadUint64(&m.afterFetchPendingsCounter) < 1 {
		return false
	}
	return true
}

// MinimockFetchPendingsInspect logs each unmet expectation
func (m *RequestsFetcherMock) MinimockFetchPendingsInspect() {
	for _, e := range m.FetchPendingsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RequestsFetcherMock.FetchPendings with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.FetchPendingsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterFetchPendingsCounter) < 1 {
		if m.FetchPendingsMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to RequestsFetcherMock.FetchPendings")
		} else {
			m.t.Errorf("Expected call to RequestsFetcherMock.FetchPendings with params: %#v", *m.FetchPendingsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcFetchPendings != nil && mm_atomic.LoadUint64(&m.afterFetchPendingsCounter) < 1 {
		m.t.Error("Expected call to RequestsFetcherMock.FetchPendings")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RequestsFetcherMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockAbortInspect()

		m.MinimockFetchPendingsInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RequestsFetcherMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RequestsFetcherMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAbortDone() &&
		m.MinimockFetchPendingsDone()
}
