{
 "title": "Insolar node",
 "tags": [ "INS" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(insolar_badger_disk_writes_total, instance)"
   },
   { "name": "role", "query": "virtual, light, heavy" }
  ]
 },
 "panels": [
  {
   "title": "Tx/S",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(insolard_messagebus_parcels_sent_count{messageType=~\"TypeCallConstructor|TypeCallMethod\", instance=~\"$node\", job=~\"$role\"}[1m]))",
     "legendFormat": "Tx/s"
    }
   ]
  },
  {
   "title": "Active Nodes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "insolard_consensus_activenodes_count{instance=~\"$node\", job=~\"$role\"}",
     "legendFormat": "{{job}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Phase 1 Packets Sent / Pulse",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(insolard_consensus_packets_sent{instance=~\"$node\", job=~\"$role\", phase=\"Phase1\"}[1m])*10",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Phase 1 Packets Recv / Pulse",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(insolard_consensus_packets_recv{instance=~\"$node\", job=~\"$role\", phase=\"phase 1\"}[1m]) * 10",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Phase 2 Packets Sent / Pulse",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(insolard_consensus_packets_sent{instance=~\"$node\", job=~\"$role\", phase=\"Phase2\"}[1m])*10",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Phase 2 Packets Recv / Pulse",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(insolard_consensus_packets_recv{instance=~\"$node\", job=~\"$role\", phase=\"phase 2\"}[1m])*10",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Phase 2.1 Packets Recv / Pulse",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 6, "y": 38 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(insolard_consensus_packets_recv{instance=~\"$node\", job=~\"$role\", phase=\"phase 21\"}[1m])*10",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Phase 3 Packets Sent / Pulse",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(insolard_consensus_packets_sent{instance=~\"$node\", job=~\"$role\", phase=\"Phase3\"}[1m])*10",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Phase 3 Packets Recv / Pulse",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(insolard_consensus_packets_recv{instance=~\"$node\", job=~\"$role\", phase=\"phase 3\"}[1m])*10",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true
  },
  {
   "title": "MessageBus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Parcels by type / sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum by(messageType) (rate(insolard_messagebus_parcels_sent_count{instance=~\"$node\", job=~\"$role\"}[1m]))",
       "legendFormat": "{{messageType}}"
      }
     ]
    },
    {
     "title": "Parcels sent / sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum by(instance, job) (rate(insolard_messagebus_parcels_sent_count{instance=~\"$node\", job=~\"$role\"}[1m]))",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Parcel delivery time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "sum (rate(insolard_messagebus_parcels_time_bucket{instance=~\"$node\", job=~\"$role\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ledger",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pending requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(insolard_hotdata_pending_total{instance=~\"$node\", job=~\"$role\"}[1m])*10",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Badger disk reads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "rate(insolar_badger_disk_reads_total{instance=~\"$node\", job=~\"$role\"}[1m])",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Redirects",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(insolard_artifactmanager_redirects{instance=~\"$node\", job=~\"$role\"}[1m])) by(service)",
       "legendFormat": "Occured on {{service}}"
      }
     ]
    },
    {
     "title": "Badger disk writes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "rate(insolar_badger_disk_writes_total{instance=~\"$node\", job=~\"$role\"}[1m])",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Records synced to heavy / sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(insolard_heavyserver_synced_records{instance=~\"$node\", job=~\"$role\"}[1m])",
       "legendFormat": "Jet {{jet}}"
      }
     ]
    }
   ]
  },
  {
   "title": "LogicRunner",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Contract methods executed /s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count (rate(insgorund_contract_execution_time_count{instance=~\"$node\", job=~\"$role\"}[100s])) by (method)"
      }
     ]
    },
    {
     "title": "Contract time by method / s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(avg(rate(insolar_goplugin_contract_execution_time_count{instance=~\"$node\", job=~\"$role\"}[100s])) by(method)) / 100",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Contract execution time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(insgorund_contract_execution_time_count{instance=~\"$node\", job=~\"$role\"}) by(instance)"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "insolar_network_connections{instance=~\"$node\", job=~\"$role\"}",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Network futures / sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum by(instance, job) (rate(insolar_network_futures{instance=~\"$node\", job=~\"$role\"}[1m]))",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Parcels sent / sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum by(instance, job) (rate(insolard_network_parcels_sent_size_count{instance=~\"$node\", job=~\"$role\"}[1m]))",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Parcels received / sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum by(instance, job) (rate(insolard_network_parcels_reply_size_count{instance=~\"$node\", job=~\"$role\"}[1m]))",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Packets sent by type / sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum by(packetType) (rate(insolar_network_packet_sent_total{instance=~\"$node\", job=~\"$role\"}[1m]))",
       "legendFormat": "{{packetType}}"
      }
     ]
    },
    {
     "title": "Packets sent / sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum by(instance, job) (rate(insolar_network_packet_sent_total{instance=~\"$node\", job=~\"$role\"}[1m]))",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Packets received by type / sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum by(packetType) (rate(insolar_network_packet_received_total{instance=~\"$node\", job=~\"$role\"}[1m]))",
       "legendFormat": "{{packetType}}"
      }
     ]
    },
    {
     "title": "Packets received / sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum by(instance) (rate(insolar_network_packet_received_total{instance=~\"$node\", job=~\"$role\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Packets timed out / sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum by(instance) (rate(insolar_network_packet_timeout_total{instance=~\"$node\", job=~\"$role\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(insolar_process_cpu_seconds_total{job=~\"$role\", endpoint=\"insolard\", instance=~\"$node\"}[1m])",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{endpoint=\"insolard\", instance=~\"$node\", job=~\"$role\"}",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Heap",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{endpoint=\"insolard\", job=~\"$role\", instance=~\"$node\"}",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Heap GC",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_gc_sys_bytes{endpoint=\"insolard\", job=~\"$role\", instance=~\"$node\"}[1m]) ",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}