// Code generated by "stringer -type=State"; DO NOT EDIT.

package pulsar

import "strconv"

const _State_name = "WaitingForTheStartWaitingForTheSignsSendingEntropyWaitingForTheEntropySendingVectorWaitingForTheVectorsVerifyingSendingSignForChosenWaitingForChosenSignsSendingEntropyToNodesFailed"

var _State_index = [...]uint8{0, 18, 36, 50, 70, 83, 103, 112, 132, 153, 174, 180}

func (i State) String() string {
	i -= 1
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
