name: master_branch_slow_test
on:
  push:
    branches:
      - master
env:
  GO_VERSION: 1.12.15
  CI_GOMAXPROCS: 0
  INSOLAR_LOG_LEVEL: warn
  GOPATH: /home/runner/work/insolar/insolar/go
jobs:
  test-slow:
    name: test-slow
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
        with:
          path: go/src/github.com/insolar/insolar
      - name: set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v1
        with:
          go-version: ${{env.GO_VERSION}}
      - name: add bin to path
        run: echo "::add-path::${{env.GOPATH}}/bin"
      - name: test_prepare
        run: |
           go mod download
           make pre-build build
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/insolar
      - name: test_slow
        run: make test_slow
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/insolar
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/insolar/insolar/go
    steps:
      - name: checkout code
        uses: actions/checkout@master
        with:
          path: go/src/github.com/insolar/insolar
      - name: set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v1
        with:
          go-version: ${{env.GO_VERSION}}
      - name: add bin to path
        run: echo "::add-path::${{env.GOPATH}}/bin"
      - name: generate codecov
        run: |
           make ci-test-with-coverage
           content=`cat coverage.txt | ./scripts/dev/cover-filter.sh`
           echo "$content" | tee $GITHUB_WORKSPACE/coverage.txt
           cat ./coverage.txt | wc
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/insolar
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.codecov_token }}
          file: ./coverage.txt
          yml:  ./codecov.yml
          fail_ci_if_error: true
